image: gcc

stages:
  - build
  - test
  - cleanup

variables:
  GITLAB_ROOT: "C:/gitlab-runner/builds/$CI_PIPELINE_ID/$CI_JOB_ID"

before_script:
  - echo "Setting up environment..."
  - New-Item -ItemType Directory -Path "$env:GITLAB_ROOT" -Force
  - Set-Location "$env:GITLAB_ROOT"
  - echo "Directory created at:` $env:GITLAB_ROOT"
  - echo "Current directory:` $(Get-Location)"

build-job:
  stage: build
  tags: [ PPE ]
  script:
    - echo "Running build job..."

unit-test-job:
  stage: test
  tags: [ PPE ]
  script:
    - echo "Running unit tests..."
    - .\runTests.bat
    - Get-Content "$env:GITLAB_ROOT/test_output.log"
    - echo "Tests finished."

cleanup-job:
  stage: cleanup
  tags: [ PPE ]
  script:
    - echo "Cleaned up
