image: gcc

stages:
  - build
  - test
  - cleanup
  - mirror

variables:
  GIT_CLONE_PATH: 'C:/gitlab-runner/builds/PPE/$CI_PIPELINE_ID/$CI_JOB_ID'
  GIT_SUBMODULE_STRATEGY: recursive

build-job:
  stage: build
  tags: [ PPE ]
  script:
    - echo "Running build job..."

unit-test-job:
  stage: test
  tags: [ PPE ]
  script:
    - echo "Running unit tests..."
    - echo "${env:CI_PROJECT_DIR}/runTests.bat"
    - Start-Process "${env:CI_PROJECT_DIR}/runTests.bat" -NoNewWindow -Wait
    - Get-Content "${env:CI_PROJECT_DIR}/test_output.log" | ForEach-Object { Write-Host $_ }
    - echo "Tests finished."

cleanup-job:
  stage: cleanup
  tags: [ PPE ]
  script:
    - echo "Cleaned up

mirror-to-github:
  stage: mirror
  tags: [ PPE ]
  script:
    - git config --global user.name "${GITHUB_USER_NAME}"
    - git config --global user.email "${GITHUB_USER_EMAIL}"
    - git clone --mirror "${CI_REPOSITORY_URL}" repo-mirror
    - cd repo-mirror
    - git remote add github "https://${GITHUB_USER_NAME}:${GITHUB_TOKEN}@github.com/astrophere/particle-physics-engine.git"
    - git push --mirror github
  only:
    - branches  # run this job on all branches
