image: gcc

stages:
  - build
  - test
  - cleanup

build-job:
  stage: build
  tags: [ PPE ]
  script:
    - echo "Running build job..."

unit-test-job:
  stage: test
  tags: [ PPE ]
  script:
    - echo "Running unit tests..."
    - echo "$env:CI_PROJECT_DIR/runTests.bat"
    - Start-Process "$env:CI_PROJECT_DIR/runTests.bat" -Wait
    - Get-Content "$env:CI_PROJECT_DIR/test_output.log"
    - echo "Tests finished."

cleanup-job:
  stage: cleanup
  tags: [ PPE ]
  script:
    - echo "Cleaned up
