image: gcc

stages:
  - build
  - test
  - cleanup

variables:
  CI_PROJECT_DIR: "C:/gitlab-runner/builds/$CI_PIPELINE_ID/$CI_JOB_ID"

build-job:
  stage: build
  tags: [ PPE ]
  script:
    - echo "Running build job..."

unit-test-job:
  stage: test
  tags: [ PPE ]
  script:
    - echo "Running unit tests..."
    - Start-Process "$env:CI_PROJECT_DIR/runTests.bat"
    - Get-Content "$env:CI_PROJECT_DIR/test_output.log"
    - echo "Tests finished."

cleanup-job:
  stage: cleanup
  tags: [ PPE ]
  script:
    - echo "Cleaned up
